---
- name: "Installing Unifi Quadlet Network"
  ansible.builtin.template:
    src: unifi-quadlet.network.j2
    dest: "{{ __unifi_netapp_quadlet_network_path }}"
    mode: "0644"
  notify:
    - daemon-reload
